### PR TITLE
Fix bug in LinearExpression.Evaluate

### LINKED ISSUE #153: LinearExpression.Evaluate is incorrect
This line is incorrect in the `LinearExpression.Evaluate` function:

https://github.com/fslaborg/flips/blob/f4df21504d015b13a837fa2f7f902c7ea0411e96/Flips/Types.fs#L236

### PR DESCRIPTION
**Pull request by TysonMN**
Fixes #153

I made two changes in order to keep the tests simple.  First, I mades things in the `Flips` project with `internal` scope visible to the `Flips.Tests` project.  Second, I weakened an argument type of the internal method `LinearExpression.Evaluate`.

It is unfortunate that these two new tests are essentially the same as the two tests above them.  This is caused by the equivalently duplicate code between `LinearExpression.Reduce` and `LinearExpression.Evaluate`.  I expect to remove that duplication one day, but not soon.

### CODE REVIEW

File: Flips/Types.fs [hunk 1]
```diff
@@ -216,7 +216,7 @@ and
             | AddLinearExpression (lExpr, rExpr) -> getRec (fun l -> getRec cont l rExpr) decisions lExpr
         getRec id Set.empty expr
 
-    static member internal Evaluate (decisionMap:Map<Decision, float>) (expr:LinearExpression) : float =
+    static member internal Evaluate (getDecisionCoef: Decision -> float) (expr:LinearExpression) : float =
```
Comment (matthewcrews) [inline Flips/Types.fs:219]: I'm curious why you went with this type versus the original `Map`?

Comment (TysonMN) [reply Flips/Types.fs:219]: `Map<'a, 'b>` is more restrictive than `'a -> 'b`.  The tests doesn't care what `Decision`s are in the `LinearExpression`s.  From the perspective of the tests, it suffices for the coefficient corresponding to each `Decision` to be `1.0`.

**Review by matthewcrews — APPROVED** [review]
